### ISSUE TITLE
'always on top' function unusable

### ISSUE THREAD

**Issue by Janrin** [infinitered/reactotron#1030]
when press menu bar  Window-> Always On Top get these error:

`
Uncaught Exception:
ReferenceError: mainWindow is not defined
    at click (/Applications/Reactotron.app/Contents/Resources/app.asar/src/webpack:/src/menu.js:157:21)
    at MenuItem.click (/Applications/Reactotron.app/Contents/Resources/electron.asar/browser/api/menu-item.js:56:9)
    at Function.executeCommand (/Applications/Reactotron.app/Contents/Resources/electron.asar/browser/api/menu.js:31:13)
`

![19_41_13__05_07_2019](https://user-images.githubusercontent.com/9426886/57296672-1eab6b00-7100-11e9-8840-09f33cc2e5eb.jpg)

**Comment by rmevans9** [comment]
Thanks for the report. I will have to dig into this to see what caused that feature to break.
