### ISSUE TITLE
Error when starting

### ISSUE THREAD

**Issue by Wellers0n** [infinitered/reactotron#1078]
```Loading dependency graph...(node:10193) UnhandledPromiseRejectionWarning: Error: jest-haste-map: @providesModule naming collision:
  Duplicate module name: react-animated
  Paths: /home/coffee/Documents/Marvel/node_modules/react-native/Libraries/Animated/release/package.json collides with /home/coffee/Documents/Marvel/packages/RNmarvel/node_modules/react-native/Libraries/Animated/release/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at setModule (/home/coffee/Documents/Marvel/node_modules/jest-haste-map/build/index.js:462:17)
    at workerReply (/home/coffee/Documents/Marvel/node_modules/jest-haste-map/build/index.js:512:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:10193) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:10193) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

I am with this error when starting

**Comment by Wellers0n** [comment]
I'm using expo,  it this is problem?

**Comment by rmevans9** [comment]
This makes it seem like there are two versions of react-native installed. Can you run `yarn why react-native` and provide the output?
