### ISSUE TITLE
OpenInEditor not working

### ISSUE THREAD

**Issue by orhangazi** [infinitered/reactotron#1248]
Hi, I looked [here](https://github.com/infinitered/reactotron/issues/1104) but I don't understand what am I missing? When I click the stack trace an error (console.error("test error")), the cursor isn't going to the line. It is sending a request to http://localhost:8081/open-stack-trace and then this is appearing on the terminal two times:
```
[Unhandled promise rejection: TypeError: Network request failed]
at node_modules\whatwg-fetch\dist\fetch.umd.js:535:17 in setTimeout$argument_0
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:123:14 in _callTimer
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:379:16 in callTimers
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:414:4 in __callFunction
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:113:6 in __guard$argument_0
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:365:10 in __guard
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:112:4 in callFunctionReturnFlushedQueue
```
The request's context:
# Request

### Endpoint

`POST` http://localhost:8081/open-stack-frame

### Duration

`56` ms

### Data Sent

```json
{
  "file": "C:\\react native uygulamaları\\test2\\ReactotronConfig.js",
  "lineNumber": 16
}
```

### Headers

key          | value                   
------------ | ------------------------
content-type | text/plain;charset=UTF-8

# Response

### Data Received

```json
 skipped 
```

ReactotronConfig.js:
```
import Reactotron, {openInEditor} from "reactotron-react-native"

Reactotron.configure({
	name: "Reactotron In Expo demo",
})
.useReactNative({
	networking: {
		//ignoreUrls: /symbolicate|127.0.0.1/,
	},
})
.configure({ host: "192.168.1.36", port: 9999 })
.use(openInEditor()) // <--- here we go!
.connect()
.clear()

console.error("config console error")
Reactotron.error("config Reactotron error")
```

Here User Environment Variable:
![image](https://user-images.githubusercontent.com/2978281/166250356-d50c5b2e-bd9f-46bc-86ef-e687c9f0ec97.png)

Here User Environment Path:
![image](https://user-images.githubusercontent.com/2978281/166251355-aafee913-bbfd-4107-b0a5-742e7295f44f.png)
I did the same things with System Environment Variable and System Environment Path.

**Comment by joshuayoes** [comment]
`openInEditor` has been broken for a little bit. The way metro works changed a few years ago. This is on the roadmap to fix
