### ISSUE TITLE
Error installing reactotron - this package itself specifies a `main` module field that could not be resolved 

### ISSUE THREAD

**Issue by fosantana** [infinitered/reactotron#888]
Hi,

I started a new project and installed the reactotron.
When I run the program it returns the message below. If I remove the import from my index.js file the error does not occur.

Can you help me?
Thanks!

ERROR--

Looking for JS files in
   /Users/flavioosantana/Documents/Aplicativos/devtools 

Loading dependency graph, done.
 BUNDLE  [ios, dev] ../../index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░ 98.9% (545/549)::1 - - [02/Dec/2018:13:36:56 +0000] "GET /index.bundle?platform=ios&dev=true&minify=false HTTP/1.1" 200 - "-" "devtools/1 CFNetwork/975.0.3 Darwin/18.2.0"
error: bundling failed: Error: While trying to resolve module `reactotron-core-client` from file `/Users/flavioosantana/Documents/Aplicativos/devtools/node_modules/reactotron-react-native/dist/index.js`, the package `/Users/flavioosantana/Documents/Aplicativos/devtools/node_modules/reactotron-core-client/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/flavioosantana/Documents/Aplicativos/devtools/node_modules/reactotron-core-client/dist/reactotron-core-client.js`. Indeed, none of these files exist:

  * `/Users/flavioosantana/Documents/Aplicativos/devtools/node_modules/reactotron-core-client/dist/reactotron-core-client.js(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
  * `/Users/flavioosantana/Documents/Aplicativos/devtools/node_modules/reactotron-core-client/dist/reactotron-core-client.js/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
    at ResolutionRequest.resolveDependency (/Users/flavioosantana/Documents/Aplicativos/devtools/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:61:15)
    at DependencyGraph.resolveDependency (/Users/flavioosantana/Documents/Aplicativos/devtools/node_modules/metro/src/node-haste/DependencyGraph.js:219:16)
    at Object.resolve (/Users/flavioosantana/Documents/Aplicativos/devtools/node_modules/metro/src/lib/transformHelpers.js:141:30)
    at dependencies.map.result (/Users/flavioosantana/Documents/Aplicativos/devtools/node_modules/metro/src/DeltaBundler/traverseDependencies.js:373:31)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/flavioosantana/Documents/Aplicativos/devtools/node_modules/metro/src/DeltaBundler/traverseDependencies.js:369:18)
    at /Users/flavioosantana/Documents/Aplicativos/devtools/node_modules/metro/src/DeltaBundler/traverseDependencies.js:188:33
    at Generator.next (<anonymous>)
    at step (/Users/flavioosantana/Documents/Aplicativos/devtools/node_modules/metro/src/DeltaBundler/traverseDependencies.js:298:30)
    at /Users/flavioosantana/Documents/Aplicativos/devtools/node_modules/metro/src/DeltaBundler/traverseDependencies.js:309:15

**Comment by fosantana** [comment]
@rmevans9 
"reactotron-core-client": {
      "version": "2.1.3",
      "resolved": "https://registry.npmjs.org/reactotron-core-client/-/reactotron-core-client-2.1.3.tgz",
      "dev": true
    },

**Comment by rmevans9** [comment]
Can you lock to version 2.1.2 and see if that resolves the issue?

**Comment by fosantana** [comment]
i'll try.
Thx

**Comment by rmevans9** [comment]
I think I see what happened with the build. I will be hopefully getting a fix out soon.

**Comment by rmevans9** [comment]
2.1.4 has been released which should fix this issue.

**Comment by fosantana** [comment]
It worked on 2.1.4! Thanks!
