### ISSUE TITLE
Starting reactotron throw an error in cli

### ISSUE THREAD

**Issue by xstable** [infinitered/reactotron#949]
I've installed Reactotron in Manjaro-Linux as package.

If I start reactotron, I got an error like this: 

> [07:13:18.057] [info] Checking for update
> [07:13:18.298] [error] Error: Error: ENOENT: no such file or directory, open '/opt/Reactotron/resources/app-update.yml'
>     at /opt/Reactotron/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:460:27
>     at Generator.next (<anonymous>)
> From previous event:
>     at AppImageUpdater.loadUpdateConfig (/opt/Reactotron/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:456:33)
>     at Lazy.AppUpdater.configOnDisk (/opt/Reactotron/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:142:43)
>     at Lazy.get value [as value] (/opt/Reactotron/resources/app.asar/node_modules/lazy-val/src/main.ts:18:23)
>     at /opt/Reactotron/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:340:46
>     at Generator.next (<anonymous>)
>     at runCallback (timers.js:696:18)
>     at tryOnImmediate (timers.js:667:5)
>     at processImmediate (timers.js:649:5)
> From previous event:
>     at AppImageUpdater.getUpdateInfoAndProvider (/opt/Reactotron/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:336:43)
>     at /opt/Reactotron/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:363:31
>     at Generator.next (<anonymous>)
> From previous event:
>     at AppImageUpdater.doCheckForUpdates (/opt/Reactotron/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:360:34)
>     at AppImageUpdater.checkForUpdates (/opt/Reactotron/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:220:35)
>     at AppImageUpdater.checkForUpdatesAndNotify (/opt/Reactotron/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:249:41)
>     at new on (/opt/Reactotron/resources/app.asar/src/webpack:/src/main.dev.js:48:5)
>     at AppUpdater (/opt/Reactotron/resources/app.asar/src/webpack:/src/main.dev.js:94:9)
>     at App.emit (events.js:187:15)
> Unhandled rejection Error: ENOENT: no such file or directory, open '/opt/Reactotron/resources/app-update.yml'
>     at /opt/Reactotron/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:460:27
>     at Generator.next (<anonymous>)
> From previous event:
>     at AppImageUpdater.loadUpdateConfig (/opt/Reactotron/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:456:33)
>     at Lazy.AppUpdater.configOnDisk (/opt/Reactotron/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:142:43)
>     at Lazy.get value [as value] (/opt/Reactotron/resources/app.asar/node_modules/lazy-val/src/main.ts:18:23)
>     at /opt/Reactotron/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:340:46
>     at Generator.next (<anonymous>)
>     at runCallback (timers.js:696:18)
>     at tryOnImmediate (timers.js:667:5)
>     at processImmediate (timers.js:649:5)
> From previous event:
>     at AppImageUpdater.getUpdateInfoAndProvider (/opt/Reactotron/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:336:43)
>     at /opt/Reactotron/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:363:31
>     at Generator.next (<anonymous>)
> From previous event:
>     at AppImageUpdater.doCheckForUpdates (/opt/Reactotron/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:360:34)
>     at AppImageUpdater.checkForUpdates (/opt/Reactotron/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:220:35)
>     at AppImageUpdater.checkForUpdatesAndNotify (/opt/Reactotron/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:249:41)
>     at new on (/opt/Reactotron/resources/app.asar/src/webpack:/src/main.dev.js:48:5)
>     at AppUpdater (/opt/Reactotron/resources/app.asar/src/webpack:/src/main.dev.js:94:9)
>     at App.emit (events.js:187:15)
>

**Comment by rmevans9** [comment]
Hmm... I am not sure what is going on here. Admittedly I don't use Linux so I will have to figure out a good way to test this to try and find a way to resolve this issue unless you are able to find a solution you can PR?
